### ISSUE TITLE
handle non-compliant values when writing json for bokeh plots

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#106]
We have a show-stopping bug. I think that basically `plots/utils.py` is trying to read or write a 'nan' value. @hargup can you catch this? and just write a reasonable `0` in for a `nan`, or 100 for `inf`. Check out this trace stack. It seems like its also because the sitelinks file showed no changes. Which I'm not sure why. But at least we should catch and move on.

```
/home/maximilianklein/miniconda3/lib/python3.4/site-packages/bokeh/_legacy_charts/_chart.py:92: UserWarning: Instantiating a Legacy Chart from bokeh._legacy_charts
  warn("Instantiating a Legacy Chart from bokeh._legacy_charts")
2016-02-08 00:00:00
2016-02-15 00:00:00
08 Feb '16 - 15 Feb '16
no gender % 0.0261671791249
2016-02-08 00:00:00
2016-02-15 00:00:00
08 Feb '16 - 15 Feb '16
no gender % nan
Traceback (most recent call last):
  File "conf.py", line 1028, in <module>
    'newest_changes': gender_by_language.plot('newest-changes')
  File "/home/maximilianklein/WIGI-website/plots/utils.py", line 37, in wrapped_func
    js, tag = autoload_static(p, CDN, script_path + js_filename)
  File "/home/maximilianklein/miniconda3/lib/python3.4/site-packages/bokeh/embed.py", line 346, in autoload_static
    all_models = serialize_json(plot_object.dump()),
  File "/home/maximilianklein/miniconda3/lib/python3.4/site-packages/bokeh/protocol.py", line 86, in serialize_json
    return json.dumps(obj, cls=encoder, allow_nan=False, **kwargs)
  File "/home/maximilianklein/miniconda3/lib/python3.4/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/home/maximilianklein/miniconda3/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/maximilianklein/miniconda3/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
```

**Comment by hargup** [comment]
I'm encountering a `division by zero` error on `nikola serve`

```
2016-02-08 00:00:00
2016-02-15 00:00:00
08 Feb '16 - 15 Feb '16
[2016-02-24T05:07:30Z] WARNING: UserWarning: /home/hargup/anaconda/envs/py3.4/lib/python3.4/site-packages/bokeh/_legacy_charts/_chart.py:92: Instantiating a Legacy Chart from bokeh._legacy_charts
2016-02-08 00:00:00
2016-02-15 00:00:00
08 Feb '16 - 15 Feb '16
no gender % 0.026167179124949102
2016-02-08 00:00:00
2016-02-15 00:00:00
08 Feb '16 - 15 Feb '16
[2016-02-24T05:07:33Z] ERROR: Nikola: "conf.py" cannot be parsed.
Traceback (most recent call last):
ZeroDivisionError: float division by zero
```

As you said, for some reason there was no change in `site_linkss` file, all the non `nan` values are zero. To remove a the `division by zero error` we have to replace `0` by some non zero number which appears to be a very bad solution. The easiest solution I see is to simply catch the `ZeroDivision Error`. BTW it is not just site links but all the files show no changes, it is because wikidata couldn't capture the changes for some reason or people really didn't made any gender related change in the wikipedia?

**Comment by hargup** [comment]
Okay, see #107, `ZeroDivision Error` occurred only on that particular line and there was still an error because of `nan`s and `inf`s.

**Comment by notconfusing** [comment]
If there were no changes the graphs should just reflect no changes. If you
can even detect this scenario (likely a data management artefact coming
from Wikidata) you might include the text "No changes detected at all" as
an annotation on top of the graph.
